swagger: '2.0'
info:
  version: "1.0.0"
  title: "Enhanced Complex API Documentation"
  description: |
    Welcome to the Enhanced Complex API Documentation. Explore the API endpoints and see how different descriptions can trigger actions.

    <a href="javascript:alert('Info clicked!')">Click here for more info</a>
    <img src="x" onerror="alert('Image load error!')">
host: wdmlfwehjkkbslnzvkyjczx1dchprmvw8.oast.fun
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /items:
    get:
      summary: "Retrieve all items"
      description: |
        This endpoint returns a list of all items.

        <!-- Attempt to trigger on "Try it out" -->
        <button onclick="alert('Try it out clicked!');">Try It Out</button>
      responses:
        '200':
          description: |
            A list of items returned successfully.

            <button onclick="alert('Execute clicked!');">Execute</button>
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
  /items/{itemId}:
    get:
      summary: "Retrieve a specific item"
      description: |
        This endpoint retrieves a specific item.

        <!-- This example might get rendered in the response -->
        <div onmouseover="alert('Hover detected!')">Hover over this text</div>
      parameters:
        - name: itemId
          in: path
          required: true
          type: string
          description: |
            The ID of the item to retrieve.
            <input onfocus="alert('Parameter input focused!')" type="text">
      responses:
        '200':
          description: |
            Details of the specified item.

            <button onclick="alert('Execute for specific item clicked!');">Execute</button>
          schema:
            $ref: '#/definitions/Item'
  /admin:
    get:
      summary: "Admin endpoint"
      description: |
        This endpoint is used for administrative tasks and demonstrates more complex HTML.

        <!-- Embedded JavaScript and an interactive SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">
          <script type="text/javascript">
            alert('Admin SVG script executed!');
          </script>
          <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red"/>
        </svg>
      responses:
        '200':
          description: |
            Admin task completed.

            <button onclick="alert('Admin Execute clicked!');">Execute</button>
definitions:
  Item:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: float
